


server:
 port: 9080
jwt:
  secret: "493358340235739058340598340598340598340598340598"
spring: 
 application:
  name: api-gateway
 cloud:
  gateway:
   # --- Configuracion de cors global ---
   globalcors:
      cors-configurations:
         '[/**]':
           allowedOrigins: "http://localhost:9080" # Permite al propio swagger del gateway
           allowedMethods:
             - GET
             - POST 
             - PUT
             - DELETE
             - OPTIONS
           allowedHeaders:

   routes:

      # RUTA PARA EL SERVICIO DE USUARIOS
      - id: usuarios-service
        uri: http://localhost:9091
        predicates:
            - Path=/api/v1/usuarios/**

      # RUTA PARA EL SERVICIO DE ALMACENES
      - id: almacenes-service
        uri: http://localhost:9092
        predicates:
        - Path=/api/v1/almacenes/**

      #RUTA PARA EL SERVICIO DE STOCK
      - id: stock-service
        uri: http://localhost:9093
        predicates:
        - Path=/api/v1/stock/**

      #RUTA PARA EL SERVICIO DE PRODUCTOS
      - id: productos-service
        uri: http://localhost:9094
        predicates:
        - Path=/api/v1/productos/**

      # RUTA PARA EL SERVICIO DE CARRITOS
      - id: carritos-service
        uri: http://localhost:9095
        predicates:
        - Path=/api/v1/carritos/**

eureka:
   client:
      register-with.eureka: false
      fetch-registry: false

springdoc:
  swagger-ui
    urls:
      - name: Servicio Usuarios 
        url: /api/v1/usuarios/**
      - name Servicio almacenes
        url: /api/v1/almacenes/**   
      - name Servicio Stock
        url: /api/v1/stock/**
      - name Servicio Carritos
        url: /api/v1/carritos/**