


server:
 port: 9080

spring: 
 application:

  name: api-gateway
 cloud:
  gateway:
   routes:

# RUTA PARA EL SERVICIO DE USUARIOS
   - id: usuarios-service
     uri: http://localhost:9091
     predicates:
      - Path=/usuarios/**

# RUTA PARA EL SERVICIO DE ALMACENES
   - id: almacenes-service
     uri: http://localhost:9092
     predicates:
     - Path=/almacenes/**

#RUTA PARA EL SERVICIO DE STOCK
   - id: stock-service
     uri: http://localhost:9093
     predicates:
     - Path=/stock/**

#RUTA PARA EL SERVICIO DE PRODUCTOS
   - id: productos-service
     uri: http://localhost:9094
     predicates:
     - Path=/productos/**

# RUTA PARA EL SERVICIO DE TRANSPORTISTAS
   - id: carritos-service
     uri: http://localhost:9095
     predicates:
     - Path=/api/v1/carritos/**
