


server:
 port: 9080

spring: 
 application:
  name: api-gateway
 cloud:
  gateway:
   # --- Configuracion de cors global ---
   globalcors:
      cors-configurations:
         '[/**]':
           allowedOrigins: "http://localhost:9080" # Permite al propio swagger del gateway
           allowedMethods:
             - GET
             - POST 
             - PUT
             - DELETE
             - OPTIONS
           allowedHeaders: "*"

   routes:

      # RUTA PARA LOS DATOS DEL SERVICIO DE USUARIOS
      - id: usuarios-service
        uri: http://localhost:9091
        predicates:
          - Path=/api/v1/usuarios/**
        filters:
          - AuthenticationFilter

      # RUTA PARA EL SERVICIO DE ALMACENES
      - id: almacenes-service
        uri: http://localhost:9092
        predicates:
          - Path=/api/v1/almacenes/**
        filters:
          - AuthenticationFilter

      #RUTA PARA EL SERVICIO DE STOCK
      - id: stock-service
        uri: http://localhost:9093
        predicates:
          - Path=/api/v1/stocks/**
        filters:
          - AuthenticationFilter

      #RUTA PARA EL SERVICIO DE PRODUCTOS
      - id: productos-service
        uri: http://localhost:9094
        predicates:
          - Path=/api/v1/productos/**
        filters:
          - AuthenticationFilter

      # RUTA PARA EL SERVICIO DE CARRITOS
      - id: carritos-service
        uri: http://localhost:9095
        predicates:
          - Path=/api/v1/carritos/**
        filters:
          - AuthenticationFilter
      
      # RUTA PARA EL SERVICIO DE COMPROBANTES
      - id: comprobantes-service
        uri: http://localhost:9096
        predicates:
          - Path=/api/v1/comprobantes/**
        filters:
          - AuthenticationFilter
      
      # RUTA PARA EL SERVICIO DE DISTRIBUIDORES
      - id: distribuidores-service
        uri: http://localhost:9097
        predicates:
          - Path=/api/v1/distribuidores/**
        filters:
          - AuthenticationFilter
      
      # RUTA PARA EL SERVICIO DE DESPACHOS
      - id: despachos-service
        uri: http://localhost:9098
        predicates:
          - Path=/api/v1/despachos/**
        filters:
          - AuthenticationFilter

      # RUTA PARA EL SERVICIO DE TRANSPORTISTAS
      - id: transportistas-service
        uri: http://localhost:9099
        predicates:
          - Path=/api/v1/transportistas/**
        filters:
          - AuthenticationFilter

      # RUTA PARA EL SERVICIO DE VENTAS
      - id: ventas-service
        uri: http://localhost:9100
        predicates:
          - Path=/api/v1/ventas/**
        filters:
          - AuthenticationFilter

       # RUTA PARA EL SERVICIO DE AUTENTICACIÓN
      - id: authentication-service
        uri: http://localhost:9101
        predicates:
        - Path=/auth/**

eureka:
   client:
      register-with.eureka: false
      fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: Servicio de Usuarios 
        url: /api/v1/usuarios/v3/api-docs
      - name: Servicio de Almacenes
        url: /api/v1/almacenes/v3/api-docs  
      - name: Servicio de Stocks
        url: /api/v1/stocks/v3/api-docs
      - name: Servicio de Carritos
        url: /api/v1/carritos/v3/api-docs
      - name: Servicio de Ventas
        url: /api/v1/ventas/v3/api-docs
      - name: Servicio de Despachos
        url: /api/v1/despachos/v3/api-docs
      - name: Servicio de Comprobantes
        url: /api/v1/comprobantes/v3/api-docs
      - name: Servicio de Transportistas
        url: /api/v1/transportistas/v3/api-docs
      - name: Servicio de Distribuidores
        url: /api/v1/distribuidores/v3/api-docs
      - name: Servicio de Productos
        url: /api/v1/productos/v3/api-docs
      - name: Servicio de Autenticación
        url: /auth/v3/api-docs

logging:

  level:

    org.springframework.cloud.gateway: TRACE

    org.springframework.http.server.reactive: DEBUG

jwt:
  secret: "493358340235739058340598340598340598340598340598"